# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
inheritance: true

reviews:
  review_status: true
  auto_review:
    enabled: true
  path_filters:
    - "!**/testdata/**/*.cassette.*"
