FROM alpine:latest

RUN apk add --no-cache \
    bash \
    build-base \
    curl \
    git \
    make \
    tree

SHELL ["/bin/ash", "-eo", "pipefail", "-c"]
RUN set -e \
    && mkdir -p /terraform-provider-katapult
WORKDIR /terraform-provider-katapult

COPY mise.toml /terraform-provider-katapult
RUN set -e \
    && curl https://mise.run | sh \
    && "$HOME/.local/bin/mise" install --yes \
    && echo 'export PS1="\u@go-alpine:\w\$ "' > /root/.bashrc \
    && echo 'alias ll="ls -lah"' >> /root/.bashrc \
    && echo 'alias ma="make"' >> /root/.bashrc \
    && echo 'alias mi="mise"' >> /root/.bashrc \
    && echo 'alias tf="terraform"' >> /root/.bashrc \
    && echo 'eval "$(~/.local/bin/mise activate bash)"' >> ~/.bashrc
