[tools]
go = "latest"
goreleaser = "2.15"
lefthook = "2.1.6"
terraform = "1.10"

[env]
# DO NOT put local environment variables here. Use mise.local.toml instead.
# Refer to mise.local.toml.example for an example.
