---
name: Nightly Acceptance Tests
concurrency: katapult.io/terraform-acc-test

on:
  schedule:
    - cron: "0 0 * * *" # Midnight every day

jobs:
  nightly:
    name: Acceptance Tests
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Run tests
        run: make testacc
        env:
          VERBOSE: "true"
          VCR: "rec"
          # TODO Remove parallel option when all parallel issues are resolved.
          TESTARGS: "-parallel=1"
          TF_LOG: DEBUG
          KATAPULT_LOG_LEVEL: DEBUG
          KATAPULT_API_KEY: ${{ secrets.KATAPULT_API_KEY }}
          KATAPULT_ORGANIZATION: ${{ secrets.KATAPULT_ORGANIZATION }}
          KATAPULT_DATA_CENTER: ${{ secrets.KATAPULT_DATA_CENTER }}
      - name: save VCR cassettes as build artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: vcr-casettes
          path: internal/provider/testdata/

  sweeper:
    runs-on: ubuntu-latest
    needs: nightly
    if: always()
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Sweep
        run: make sweep
        env:
          KATAPULT_API_KEY: ${{ secrets.KATAPULT_API_KEY }}
          KATAPULT_ORGANIZATION: ${{ secrets.KATAPULT_ORGANIZATION }}
          KATAPULT_DATA_CENTER: ${{ secrets.KATAPULT_DATA_CENTER }}
